name: Infinity-X Build gta4l
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Free Space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Setup Env
        run: |
          sudo apt update
          sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Build ROM
        run: |
          git config --global user.email "tabmohamedpro@gmail.com"
          git config --global user.name "Mkpromypro"
          mkdir build && cd build
          repo init -u https://github.com/ProjectInfinity-X/manifest -b 15 --depth=1
          mkdir -p .repo/local_manifests
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="LineageOS/android_device_samsung_gta4l" path="device/samsung/gta4l" remote="github" revision="lineage-22.1" />
            <project name="LineageOS/android_device_samsung_gta4l-common" path="device/samsung/gta4l-common" remote="github" revision="lineage-22.1" />
            <project name="LineageOS/android_kernel_samsung_sm6115" path="kernel/samsung/sm6115" remote="github" revision="lineage-22.1" />
            <project name="TheMuppets/proprietary_vendor_samsung_gta4l" path="vendor/samsung/gta4l" remote="github" revision="lineage-22.1" />
            <project name="TheMuppets/proprietary_vendor_samsung_gta4l-common" path="vendor/samsung/gta4l-common" remote="github" revision="lineage-22.1" />
          </manifest>' > .repo/local_manifests/gta4l.xml
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          source build/envsetup.sh
          lunch infinity_gta4l-ap3a-userdebug
          mka bacon
